# Generated by Django 3.1.5 on 2021-01-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaidApp', '0002_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='AccountModel',
        ),
    ]
