# Generated by Django 3.1.5 on 2021-01-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaidApp', '0003_auto_20210113_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
