# Generated by Django 3.1.5 on 2021-01-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaidApp', '0006_auto_20210113_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200, unique=True)),
                ('api_type', models.CharField(max_length=200)),
            ],
        ),
    ]
