# Generated by Django 3.1.5 on 2021-01-14 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlaidApp', '0007_apilogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogmodel',
            name='date_log',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_log '),
            preserve_default=False,
        ),
    ]
